/**
 * @generated by @lili/product 0.0.0
 * product: workers@1.0.0
 * canonical-catalog-digest: sha256:de12f799dd0d9df13d4c580e45a85dbacec48854728853a8c110d1e0b6a9d484
 * generation-options-digest: sha256:ae927f0ecd0037fa650399362e99eb64460bfbd80a73927b51c8f20a3c0907ad
 * surface-id: cli
 * source: catalog
 *
 * Do not edit by hand. Regenerate via `li-product generate`.
 */

import { Cli, Config, callHttpOperation, z } from '@lili/core'
import { deploy, dev } from './impl/wrangler.js'

const script = Cli.create('script')
  .command('list', {
    auth: { required: false, status: 'not-required', requiredPermissions: ['workers:read'], requiredScopes: ['workers.read'] },
    options: z.object({}),
    output: z.array(z.object({
      'created_at': z.string().optional(),
      'id': z.string(),
      'name': z.string(),
    })),
    async run(ctx) {
      const data = await callHttpOperation({
        id: 'script.list',
        baseUrl: ctx.config['apiBaseUrl'] as string,
        auth: { kind: 'none' },
        method: 'GET',
        path: '',
        bind: { body: false },
        input: ctx.options as Record<string, unknown>,
        inputFields: [],
        output: z.array(z.object({
          'created_at': z.string().optional(),
          'id': z.string(),
          'name': z.string(),
        })),
        env: ctx.env as Record<string, string | undefined>,
      })
      return ctx.ok(data, { execution: { mode: 'remote-http', source: 'schema-default' } })
    },
  })

const cli = Cli.create({
  name: 'workers',
  version: '1.0.0',
  generated: { machineOutput: 'envelope', disabledGlobals: ['format'] },
  config: Config.object({
    files: ['workers.jsonc', 'workers.yaml', 'workers.toml'],
    schema: z.strictObject({
      'accountId': z.string().optional(),
      'apiBaseUrl': z.string().default("https://api.cloudflare.test"),
    }),
    scopes: { project: { discoverUpwards: true }, user: { xdg: true } },
  }),
})
  .command(script)
  .command('deploy', {
    auth: { required: false, status: 'not-required', requiredPermissions: ['workers:edit'], requiredScopes: ['workers.edit'] },
    options: z.object({
      'entrypoint': z.string(),
      'environment': z.string().optional(),
    }),
    output: z.object({
      'deployment_id': z.string(),
      'url': z.string().optional(),
    }),
    async run(ctx) {
      const data = await deploy(ctx.options)
      return ctx.ok(data, { execution: { mode: 'hybrid-workflow', source: 'schema-default' } })
    },
  })
  .command('dev', {
    options: z.object({
      'entrypoint': z.string(),
    }),
    output: z.object({
      'url': z.string(),
    }),
    async run(ctx) {
      const data = await dev(ctx.options)
      return ctx.ok(data, { execution: { mode: 'local', source: 'schema-default' } })
    },
  })

export default cli
