/**
 * @generated by @lili/product 0.0.0
 * product: workers@1.0.0
 * canonical-catalog-digest: sha256:19302d8458e264fd82f1945dec540d67e29d7cdc261aa56f76c4ae839abf4115
 * generation-options-digest: sha256:ae927f0ecd0037fa650399362e99eb64460bfbd80a73927b51c8f20a3c0907ad
 * surface-id: cli
 * source: catalog
 *
 * Do not edit by hand. Regenerate via `li-product generate`.
 */

import { Config, callHttpOperation, createLocalTelemetrySink, defineCli, defineCommand, runLocalDoctor, z } from '@lili/core'
import { deploy, dev } from './impl/wrangler.js'

const PRODUCT_ID = 'workers'
const DOCTOR_PACKAGE_MANAGERS = ['bun', 'npm'] as const
const TELEMETRY_ENABLED_ENV_VAR = 'WORKERS_TELEMETRY'
const TELEMETRY_FILE_ENV_VAR = 'WORKERS_TELEMETRY_FILE'

const GENERATED_CATALOG = {
  "kind": "lili.catalog",
  "catalogVersion": 1,
  "product": {
    "id": "workers",
    "name": "Workers",
    "version": "1.0.0",
    "description": "Build and deploy serverless applications."
  },
  "vocabulary": {
    "verbs": [
      "get",
      "list",
      "create",
      "update",
      "delete",
      "run"
    ],
    "flags": [
      "json",
      "local",
      "remote",
      "force"
    ],
    "aliases": {}
  },
  "ops": {
    "enabled": true,
    "doctor": {
      "packageManagers": [
        "bun",
        "npm"
      ]
    },
    "telemetry": {
      "enabledEnvVar": "WORKERS_TELEMETRY",
      "fileEnvVar": "WORKERS_TELEMETRY_FILE"
    },
    "notices": {
      "updates": [
        {
          "id": "workers-cli-1.1.0",
          "severity": "info",
          "message": "Workers CLI 1.1.0 is available on the stable channel.",
          "since": "2026-05-21"
        }
      ],
      "channels": [
        {
          "id": "workers-next-channel",
          "severity": "info",
          "message": "Use the next channel for generated remote command previews."
        }
      ],
      "yanks": [
        {
          "id": "workers-cli-0.9.0",
          "severity": "warning",
          "message": "Workers CLI 0.9.0 was yanked due to a packaging regression."
        }
      ]
    }
  },
  "auth": {
    "kind": "none"
  },
  "permissions": [
    {
      "id": "workers:edit",
      "scope": "workers.edit"
    },
    {
      "id": "workers:read",
      "scope": "workers.read"
    }
  ],
  "contexts": [],
  "config": {
    "files": [
      "workers.jsonc",
      "workers.yaml",
      "workers.toml"
    ],
    "scopes": {
      "project": {
        "discoverUpwards": true
      },
      "user": {
        "xdg": true
      }
    },
    "fields": {
      "kind": "object",
      "properties": {
        "apiBaseUrl": {
          "type": "string",
          "description": "API base URL",
          "required": true,
          "secret": false,
          "identifier": false,
          "humanLabel": false,
          "mutability": "mutable",
          "default": "https://api.cloudflare.test"
        },
        "accountId": {
          "type": "string",
          "description": "Default account ID",
          "required": false,
          "secret": false,
          "identifier": false,
          "humanLabel": false,
          "mutability": "mutable"
        }
      },
      "jsonSchema": {
        "type": "object",
        "properties": {
          "apiBaseUrl": {
            "type": "string",
            "description": "API base URL",
            "default": "https://api.cloudflare.test"
          },
          "accountId": {
            "type": "string",
            "description": "Default account ID"
          }
        },
        "required": [
          "apiBaseUrl"
        ]
      }
    }
  },
  "remote": {
    "baseUrl": {
      "kind": "config",
      "path": "apiBaseUrl"
    }
  },
  "resources": [
    {
      "id": "script",
      "label": "Worker script",
      "path": "/workers/scripts",
      "fields": {
        "id": {
          "type": "string",
          "description": "Script ID",
          "required": true,
          "secret": false,
          "identifier": true,
          "humanLabel": false,
          "mutability": "immutable"
        },
        "name": {
          "type": "string",
          "description": "Script name",
          "required": true,
          "secret": false,
          "identifier": false,
          "humanLabel": true,
          "mutability": "mutable"
        },
        "created_at": {
          "type": "datetime",
          "description": "Creation time",
          "required": false,
          "secret": false,
          "identifier": false,
          "humanLabel": false,
          "mutability": "immutable"
        }
      },
      "scope": "account"
    }
  ],
  "bindings": [
    {
      "key": "kv_namespaces",
      "fields": {
        "kind": "object",
        "properties": {
          "binding": {
            "type": "string",
            "description": "Variable name in code",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          },
          "id": {
            "type": "string",
            "description": "KV namespace id",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          }
        },
        "jsonSchema": {
          "type": "object",
          "properties": {
            "binding": {
              "type": "string",
              "description": "Variable name in code"
            },
            "id": {
              "type": "string",
              "description": "KV namespace id"
            }
          },
          "required": [
            "binding",
            "id"
          ]
        }
      },
      "doc": "KV namespaces bound to the Worker."
    }
  ],
  "capabilities": [
    {
      "kind": "resource-operation",
      "id": "script.list",
      "resourceId": "script",
      "verb": "list",
      "command": [
        "script",
        "list"
      ],
      "summary": "List Worker scripts",
      "examples": [
        {
          "command": "workers script list --json"
        }
      ],
      "output": {
        "kind": "list",
        "resourceId": "script"
      },
      "requires": {
        "auth": false,
        "contexts": [],
        "permissions": [
          "workers:read"
        ]
      },
      "surfaces": {
        "cli": true,
        "docs": true,
        "dashboard": false,
        "agent": false,
        "openapi": true
      },
      "effects": {
        "kind": "read",
        "idempotent": true
      },
      "policy": {
        "dangerous": false,
        "requiresConfirmation": false,
        "conformanceEligible": true
      },
      "http": {
        "method": "GET",
        "path": "",
        "bind": {
          "path": [],
          "query": [],
          "headers": {},
          "body": false
        }
      }
    },
    {
      "kind": "command",
      "id": "deploy",
      "family": "workflow",
      "command": [
        "deploy"
      ],
      "summary": "Deploy a Worker",
      "examples": [
        {
          "command": "workers deploy --entrypoint src/index.ts --environment preview --json"
        }
      ],
      "execution": {
        "mode": "hybrid-workflow",
        "handler": "wrangler.deploy",
        "steps": [
          {
            "id": "bundle",
            "label": "Bundle local source",
            "uses": "local"
          },
          {
            "id": "upload",
            "label": "Upload assets",
            "uses": "api"
          }
        ]
      },
      "requires": {
        "auth": false,
        "contexts": [],
        "permissions": [
          "workers:edit"
        ]
      },
      "surfaces": {
        "cli": true,
        "docs": true,
        "dashboard": false,
        "agent": false,
        "openapi": false
      },
      "effects": {
        "kind": "exec",
        "idempotent": false
      },
      "policy": {
        "dangerous": true,
        "requiresConfirmation": true,
        "conformanceEligible": false
      },
      "input": {
        "kind": "object",
        "properties": {
          "entrypoint": {
            "type": "string",
            "description": "Entrypoint file",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          },
          "environment": {
            "type": "string",
            "description": "Environment",
            "required": false,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          }
        },
        "jsonSchema": {
          "type": "object",
          "properties": {
            "entrypoint": {
              "type": "string",
              "description": "Entrypoint file"
            },
            "environment": {
              "type": "string",
              "description": "Environment"
            }
          },
          "required": [
            "entrypoint"
          ]
        }
      },
      "output": {
        "kind": "object",
        "properties": {
          "deployment_id": {
            "type": "string",
            "description": "Deployment ID",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          },
          "url": {
            "type": "string",
            "description": "Deployment URL",
            "required": false,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          }
        },
        "jsonSchema": {
          "type": "object",
          "properties": {
            "deployment_id": {
              "type": "string",
              "description": "Deployment ID"
            },
            "url": {
              "type": "string",
              "description": "Deployment URL"
            }
          },
          "required": [
            "deployment_id"
          ]
        }
      }
    },
    {
      "kind": "command",
      "id": "dev",
      "family": "dev",
      "command": [
        "dev"
      ],
      "summary": "Run a local development server",
      "examples": [],
      "execution": {
        "mode": "local",
        "handler": "wrangler.dev",
        "needs": [
          "filesystem",
          "runtime"
        ]
      },
      "requires": {
        "auth": false,
        "contexts": [],
        "permissions": []
      },
      "surfaces": {
        "cli": true,
        "docs": true,
        "dashboard": false,
        "agent": false,
        "openapi": false
      },
      "input": {
        "kind": "object",
        "properties": {
          "entrypoint": {
            "type": "string",
            "description": "Entrypoint file",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          }
        },
        "jsonSchema": {
          "type": "object",
          "properties": {
            "entrypoint": {
              "type": "string",
              "description": "Entrypoint file"
            }
          },
          "required": [
            "entrypoint"
          ]
        }
      },
      "output": {
        "kind": "object",
        "properties": {
          "url": {
            "type": "string",
            "description": "Local URL",
            "required": true,
            "secret": false,
            "identifier": false,
            "humanLabel": false,
            "mutability": "mutable"
          }
        },
        "jsonSchema": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "description": "Local URL"
            }
          },
          "required": [
            "url"
          ]
        }
      }
    }
  ]
} as const
const STATIC_NOTICES = {
  "updates": [
    {
      "id": "workers-cli-1.1.0",
      "severity": "info",
      "message": "Workers CLI 1.1.0 is available on the stable channel.",
      "since": "2026-05-21"
    }
  ],
  "channels": [
    {
      "id": "workers-next-channel",
      "severity": "info",
      "message": "Use the next channel for generated remote command previews."
    }
  ],
  "yanks": [
    {
      "id": "workers-cli-0.9.0",
      "severity": "warning",
      "message": "Workers CLI 0.9.0 was yanked due to a packaging regression."
    }
  ]
} as const

const cli = defineCli({
  name: 'workers',
  version: '1.0.0',
  generated: { machineOutput: 'envelope', disabledGlobals: ['format'] },
  events: [createLocalTelemetrySink({ enabledEnvVar: TELEMETRY_ENABLED_ENV_VAR, fileEnvVar: TELEMETRY_FILE_ENV_VAR })],
  config: Config.object({
    files: ['workers.jsonc', 'workers.yaml', 'workers.toml'],
    schema: z.strictObject({
      'accountId': z.string().optional(),
      'apiBaseUrl': z.string().default("https://api.cloudflare.test"),
    }),
    scopes: { project: { discoverUpwards: true }, user: { xdg: true } },
  }),
  commands: [
    defineCommand({
      path: ['script', 'list'],
      agent: false,
      summary: 'List Worker scripts',
      examples: [{ command: 'workers script list --json' }],
      effects: { kind: 'read', idempotent: true },
      policy: { dangerous: false, requiresConfirmation: false, conformanceEligible: true },
      auth: { required: false, status: 'not-required', requiredPermissions: ['workers:read'], requiredScopes: ['workers.read'] },
      input: {
        options: z.object({}),
      },
      output: z.array(z.object({
        'created_at': z.string().optional(),
        'id': z.string(),
        'name': z.string(),
      })),
      safety: { auth: 'none', destructive: false, idempotent: true, interactive: 'never', openWorld: true, readOnly: true },
      async run({ ctx }) {
        const remoteBaseUrl = ctx.config['apiBaseUrl']
        if (typeof remoteBaseUrl !== 'string' || remoteBaseUrl.length === 0) {
          return ctx.error({
            code: 'REMOTE_CONFIG_MISSING_BASE_URL',
            message: 'Remote base URL is required.',
          })
        }
        const remoteBaseUrlSource = ctx.sources.config('apiBaseUrl').kind === 'default' ? 'schema-default' : 'config'
        const data = await callHttpOperation({
          id: 'script.list',
          baseUrl: remoteBaseUrl,
          auth: { kind: 'none' },
          method: 'GET',
          path: '',
          bind: { body: false },
          input: ctx.options as Record<string, unknown>,
          inputFields: [],
          output: z.array(z.object({
            'created_at': z.string().optional(),
            'id': z.string(),
            'name': z.string(),
          })),
          env: ctx.env as Record<string, string | undefined>,
          requiredPermissions: ['workers:read'],
        })
        return ctx.ok(data, { execution: { mode: 'remote-http', source: remoteBaseUrlSource } })
      },
    }),
    defineCommand({
      path: ['deploy'],
      agent: false,
      summary: 'Deploy a Worker',
      examples: [{ command: 'workers deploy --entrypoint src/index.ts --environment preview --json' }],
      effects: { kind: 'exec', idempotent: false },
      policy: { dangerous: true, requiresConfirmation: true, conformanceEligible: false },
      auth: { required: false, status: 'not-required', requiredPermissions: ['workers:edit'], requiredScopes: ['workers.edit'] },
      input: {
        options: z.object({
          'entrypoint': z.string(),
          'environment': z.string().optional(),
        }),
      },
      output: z.object({
        'deployment_id': z.string(),
        'url': z.string().optional(),
      }),
      safety: { auth: 'none', destructive: true, idempotent: false, interactive: 'never', openWorld: true, readOnly: false },
      async run({ ctx }) {
        const data = await deploy(ctx.options)
        return ctx.ok(data, { execution: { mode: 'hybrid-workflow', source: 'schema-default' } })
      },
    }),
    defineCommand({
      path: ['dev'],
      agent: false,
      summary: 'Run a local development server',
      input: {
        options: z.object({
          'entrypoint': z.string(),
        }),
      },
      output: z.object({
        'url': z.string(),
      }),
      safety: { auth: 'none', destructive: false, idempotent: false, interactive: 'never', openWorld: false, readOnly: false },
      async run({ ctx }) {
        const data = await dev(ctx.options)
        return ctx.ok(data, { execution: { mode: 'local', source: 'schema-default' } })
      },
    }),
    defineCommand({
      path: ['doctor'],
      agent: true,
      summary: 'Run local installation and PATH diagnostics.',
      input: { env: z.object({ 'PATH': z.string().optional() }) },
      output: z.unknown(),
      safety: { auth: 'none', destructive: false, idempotent: true, interactive: 'never', openWorld: false, readOnly: true },
      async run({ ctx }) {
        return await runLocalDoctor({
          cliName: PRODUCT_ID,
          version: '1.0.0',
          env: ctx.env as Record<string, string | undefined>,
          packageManagers: DOCTOR_PACKAGE_MANAGERS,
        })
      },
    }),
    defineCommand({
      path: ['catalog'],
      agent: true,
      summary: 'Print the generated local catalog artifact.',
      output: z.unknown(),
      safety: { auth: 'none', destructive: false, idempotent: true, interactive: 'never', openWorld: false, readOnly: true },
      run() { return GENERATED_CATALOG },
    }),
    defineCommand({
      path: ['notices'],
      agent: true,
      summary: 'Print static update, channel, and yank notices.',
      output: z.unknown(),
      safety: { auth: 'none', destructive: false, idempotent: true, interactive: 'never', openWorld: false, readOnly: true },
      run() { return STATIC_NOTICES },
    }),
    defineCommand({
      path: ['telemetry'],
      agent: true,
      summary: 'Show local telemetry sink status.',
      input: { env: z.object({
        [TELEMETRY_ENABLED_ENV_VAR]: z.string().optional(),
        [TELEMETRY_FILE_ENV_VAR]: z.string().optional(),
      }) },
      output: z.unknown(),
      safety: { auth: 'none', destructive: false, idempotent: true, interactive: 'never', openWorld: false, readOnly: true },
      run({ ctx }) {
        const raw = ctx.env[TELEMETRY_ENABLED_ENV_VAR]
        const enabled = raw !== undefined && raw !== '' && raw !== '0' && raw.toLowerCase() !== 'false'
        return {
          enabled,
          sink: ctx.env[TELEMETRY_FILE_ENV_VAR] ? { kind: 'file', path: ctx.env[TELEMETRY_FILE_ENV_VAR] } : undefined,
          redaction: 'enabled',
        }
      },
    }),
  ],
})

export default cli
