import type { CliState } from '../types.js'
import { collectCommandContracts } from './registry.js'

export function renderTypegen(name: string, state: CliState): string {
  const entries = collectCommandContracts(state.commands, state.root)
  const records = entries
    .map((entry) => {
      const schema = entry.schema as { args?: unknown; options?: unknown } | undefined
      return `    ${JSON.stringify(entry.name)}: { args: ${literal(schema?.args)}; options: ${literal(schema?.options)} }`
    })
    .join('\n')

  return [
    `// Generated by \`${name} gen\`. Do not edit by hand.`,
    `// Re-run after changing command definitions.`,
    ``,
    `declare module '@lili/core' {`,
    `  namespace Cli {`,
    `    interface Commands {`,
    records,
    `    }`,
    `  }`,
    `}`,
    ``,
    `export {}`,
    ``,
  ].join('\n')
}

function literal(value: unknown): string {
  if (value === undefined) return 'undefined'
  return JSON.stringify(value).replace(/\*\//g, '*\\/')
}
