import type { Catalog } from '../../catalog/types.js'
import { renderCli } from './capability.js'
import { renderImports } from './imports.js'
import {
  authRuntimeUsed,
  contextRuntimeUsed,
  missingRemoteError,
  opsRuntimeUsed,
} from './predicates.js'
import {
  renderCatalogConstants,
  renderProductDoctorHelpers,
  renderRuntimeConstants,
} from './runtime.js'

export type GenerateOptions = {
  generatorVersion: string
  canonicalIrDigest: string
  generationOptionsDigest: string
  surfaceId?: string
}

export function generateCli(catalog: Catalog, options: GenerateOptions): string {
  assertRemoteTransportReady(catalog)
  const lines: string[] = []
  lines.push(...renderHeader(catalog, options))
  lines.push('')
  lines.push(...renderImports(catalog))
  if (authRuntimeUsed(catalog) || contextRuntimeUsed(catalog) || opsRuntimeUsed(catalog)) {
    lines.push('')
    lines.push(...renderRuntimeConstants(catalog))
  }
  if (catalog.ops.enabled) {
    lines.push('')
    lines.push(...renderCatalogConstants(catalog))
    if (catalog.ops.doctor !== false) {
      lines.push('')
      lines.push(...renderProductDoctorHelpers())
    }
  }
  lines.push('')
  lines.push(...renderCli(catalog))
  lines.push('')
  return lines.join('\n')
}

function assertRemoteTransportReady(catalog: Catalog): void {
  for (const cap of catalog.capabilities) {
    if (cap.kind === 'resource-operation') {
      if (!cap.http) {
        throw new Error(
          `Generated CLI cannot render resource operation '${cap.id}' because it has no HTTP transport.`,
        )
      }
      if (!catalog.remote) throw missingRemoteError(cap.id)
      continue
    }
    if (cap.execution.mode === 'remote-http' && !catalog.remote) throw missingRemoteError(cap.id)
  }
}

function renderHeader(catalog: Catalog, options: GenerateOptions): string[] {
  return [
    '/**',
    ` * @generated by @liche/product ${options.generatorVersion}`,
    ` * product: ${catalog.product.id}@${catalog.product.version}`,
    ` * canonical-catalog-digest: ${options.canonicalIrDigest}`,
    ` * generation-options-digest: ${options.generationOptionsDigest}`,
    ` * surface-id: ${options.surfaceId ?? 'cli'}`,
    ' * source: catalog',
    ' *',
    ' * Do not edit by hand. Regenerate via `liche-product generate`.',
    ' */',
  ]
}
