export { normalizeProduct } from './normalize.js'
export { fieldToJsonSchema, resolveListShape } from './shape.js'
export type { ResolvedListShape } from './shape.js'
export type {
  Capability,
  Catalog,
  CommandCapability,
  NormalizedAuth,
  NormalizedBinding,
  NormalizedCapabilityExample,
  NormalizedConfig,
  NormalizedConfigScopes,
  NormalizedContext,
  NormalizedContextSelect,
  NormalizedEffects,
  NormalizedExecution,
  NormalizedHttpBind,
  NormalizedHttpSpec,
  NormalizedListShape,
  NormalizedObjectShape,
  NormalizedOps,
  NormalizedPermission,
  NormalizedPolicy,
  NormalizedProductScope,
  NormalizedRemote,
  NormalizedRequires,
  NormalizedResource,
  NormalizedRuntimeValue,
  NormalizedShape,
  NormalizedSurfaces,
  NormalizedTokenSource,
  NormalizedVocabulary,
  NormalizedWorkflowStep,
  ResourceOperationCapability,
} from './types.js'
