import { describe, expect, test } from 'bun:test'
import {
  Auth,
  Command,
  createConfig,
  Field,
  Runtime,
  Shape,
  canonicalDigest,
  defineProduct,
  generateCli,
  normalizeProduct,
} from '../../../src/index.js'
import type { Catalog } from '../../../src/index.js'

function workersCatalog(): Catalog {
  const product = defineProduct({
    id: 'workers',
    name: 'Workers',
    version: '1.0.0',
    auth: Auth.none(),
    remote: { baseUrl: Runtime.literal('https://api.example.test') },
    resources: {
      script: {
        label: 'Worker script',
        path: '/workers/scripts',
        fields: {
          id: Field.string('Script ID').identifier().immutable(),
          name: Field.string('Script name').humanLabel(),
        },
        operations: {
          list: {
          summary: 'List Worker scripts',
          http: { method: 'GET', path: '' },
          output: Shape.list('script'),
          },
        },
      },
    },
    commands: {
      deploy: Command.workflow({
        summary: 'Deploy a Worker',
        input: Shape.object({
          entrypoint: Field.string('Entrypoint file'),
          environment: Field.string('Environment').optional(),
        }),
        output: Shape.object({ deployment_id: Field.string('Deployment ID') }),
        handler: 'wrangler.deploy',
      }),
      dev: Command.local({
        summary: 'Run a local development server',
        input: Shape.object({ entrypoint: Field.string('Entrypoint file') }),
        output: Shape.object({ url: Field.string('Local URL') }),
        handler: 'wrangler.dev',
      }),
    },
  })
  return normalizeProduct(product)
}

function generate(catalog: Catalog): string {
  return generateCli(catalog, {
    generatorVersion: '0.0.0',
    canonicalIrDigest: canonicalDigest(catalog),
    generationOptionsDigest: canonicalDigest({ surfaceId: 'cli' }),
  })
}

describe('generateCli — header', () => {
  test('header records source=catalog and product@version, not contract@version', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(' * @generated by @liche/product 0.0.0')
    expect(source).toContain(' * product: workers@1.0.0')
    expect(source).toContain(' * canonical-catalog-digest:')
    expect(source).toContain(' * source: catalog')
    expect(source).not.toContain('schema: workers')
    expect(source).not.toContain('source: canonical-ir')
  })
})

describe('generateCli — imports', () => {
  test('imports defineCli, defineCommand, standard controls, and z from @liche/core exactly once', () => {
    const source = generate(workersCatalog())
    const coreImports = [...source.matchAll(/from '@liche\/core'/g)]
    expect(coreImports).toHaveLength(1)
    const importLine = source.match(/import \{ ([^}]+) \} from '@liche\/core'/)
    expect(importLine?.[1]).toBe('callHttpOperation, defineCli, defineCommand, help, outputControls, reflectionControls, version, z')
  })

  test('local and hybrid-workflow handlers are imported from ./impl/<module>.js, grouped per module', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`import { deploy, dev } from './impl/wrangler.js'`)
  })

  test('no handler imports are emitted for resource operations (HTTP, no handler binding)', () => {
    const source = generate(workersCatalog())
    expect(source).not.toMatch(/from '\.\/impl\/script\.js'/)
  })

  test('two distinct handler modules emit two grouped import lines in module-sorted order', () => {
    const cat = normalizeProduct(
      defineProduct({
        id: 'p',
        name: 'P',
        version: '0.1.0',
        auth: Auth.none(),
        commands: {
          login: Command.local({ summary: 'login', handler: 'auth.login' }),
          dev: Command.local({ summary: 'dev', handler: 'wrangler.dev' }),
        },
      }),
    )
    const source = generate(cat)
    const authIdx = source.indexOf(`from './impl/auth.js'`)
    const wranglerIdx = source.indexOf(`from './impl/wrangler.js'`)
    expect(authIdx).toBeGreaterThan(-1)
    expect(wranglerIdx).toBeGreaterThan(-1)
    expect(authIdx).toBeLessThan(wranglerIdx)
  })

  test('handler strings must be of the form module.export; bare strings fail loudly', () => {
    const product = defineProduct({
      id: 'p',
      name: 'P',
      version: '0.1.0',
      auth: Auth.none(),
      commands: {
        dev: Command.local({ summary: 'dev', handler: 'broken' }),
      },
    })
    expect(() => generate(normalizeProduct(product))).toThrow(
      /Handler 'broken' must be of the form 'module\.export'/,
    )
  })
})

describe('generateCli — command tree shape', () => {
  test('resource operations are declared with explicit nested paths', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`const cli = defineCli({`)
    expect(source).toContain(`path: ['script', 'list'],`)
    expect(source).not.toContain(`Cli.create`)
    expect(source).not.toContain(`.command(`)
  })

  test('top-level commands are declared in the same command array without sub-Cli wrappers', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`path: ['deploy'],`)
    expect(source).toContain(`path: ['dev'],`)
    expect(source).not.toContain(`const deploy = Cli.create('deploy')`)
    expect(source).not.toContain(`const dev = Cli.create('dev')`)
  })

  test('root defineCli carries product id+version and explicit generated controls', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`const cli = defineCli({`)
    expect(source).toContain(`  name: 'workers',`)
    expect(source).toContain(`  version: '1.0.0',`)
    expect(source).toContain(`  generated: { machineOutput: 'envelope' },`)
    expect(source).toContain(`help()`)
    expect(source).toContain(`outputControls({ json: true, fullOutput: true, filterOutput: true })`)
    expect(source).toContain(`reflectionControls({ schema: true })`)
    expect(source).toContain(`llms({ commands: { include: [] } })`)
    expect(source).not.toContain(`tokens()`)
  })
})

describe('generateCli — run bodies by execution mode', () => {
  test('local command run body calls the exported handler with ctx.options and tags meta.execution.mode=local', () => {
    const source = generate(workersCatalog())
    // The dev command should look like: const data = await dev(ctx.options); return ctx.ok(data, { execution: { mode: 'local', ...
    const devBlock = extractCommandBlock(source, 'dev')
    expect(devBlock).toMatch(/const data = await dev\(ctx\.options\)/)
    expect(devBlock).toMatch(/execution: \{ mode: 'local', source: 'schema-default' \}/)
  })

  test('hybrid-workflow command run body calls the handler and tags meta.execution.mode=hybrid-workflow', () => {
    const source = generate(workersCatalog())
    const deployBlock = extractCommandBlock(source, 'deploy')
    expect(deployBlock).toMatch(/const data = await deploy\(ctx\.options\)/)
    expect(deployBlock).toMatch(/execution: \{ mode: 'hybrid-workflow', source: 'schema-default' \}/)
  })

  test('resource operation run body calls core HTTP transport', () => {
    const source = generate(workersCatalog())
    const listBlock = extractCommandBlock(source, ['script', 'list'])
    expect(listBlock).toContain(`const data = await callHttpOperation({`)
    expect(listBlock).toContain(`baseUrl: 'https://api.example.test',`)
    expect(listBlock).toContain(`method: 'GET',`)
    expect(listBlock).toContain(`path: '',`)
    expect(listBlock).toContain(`bind: { body: false },`)
    expect(listBlock).toContain(`execution: { mode: 'remote-http', source: 'schema-default' }`)
    expect(listBlock).not.toContain(`REMOTE_NOT_IMPLEMENTED`)
    expect(listBlock).not.toMatch(/await \w+\(ctx\.options\)/)
  })

  test('remote-http command without product remote fails generation instead of emitting a stub', () => {
    const cat = normalizeProduct(
      defineProduct({
        id: 'p',
        name: 'P',
        version: '0.1.0',
        auth: Auth.none(),
        commands: {
          purge: Command.remoteHttp({ summary: 'Purge', http: { method: 'POST', path: '/purge' } }),
        },
      }),
    )
    expect(() => generate(cat)).toThrow(
      "Generated CLI cannot render HTTP capability 'purge' without defineProduct({ remote: { baseUrl } }).",
    )
  })

  test('remote-http command with product remote config calls core HTTP transport', () => {
    const cat = normalizeProduct(
      defineProduct({
        id: 'p',
        name: 'P',
        version: '0.1.0',
        auth: Auth.none(),
        config: createConfig({
          files: ['p.jsonc'],
          fields: Shape.object({
            apiBaseUrl: Field.string('API base URL').default('https://api.example.test'),
            defaultZone: Field.string('Default zone').optional(),
          }),
          scopes: { project: { discoverUpwards: true }, user: false },
        }),
        remote: { baseUrl: Runtime.config('apiBaseUrl') },
        commands: {
          purge: Command.remoteHttp({
            summary: 'Purge',
            input: Shape.object({
              zone: Field.string('Zone').fromConfig('defaultZone'),
            }),
            output: Shape.object({ purge_id: Field.string('Purge ID') }),
            http: { method: 'POST', path: '/zones/{zone}/purge', bind: { path: ['zone'] } },
          }),
        },
      }),
    )
    const source = generate(cat)
    expect(source.match(/from '@liche\/core'/)?.[0]).toBe("from '@liche/core'")
    expect(source).toContain(`import { callHttpOperation, defineCli, defineCommand, help, outputControls, reflectionControls, version, z } from '@liche/core'`)
    expect(source).toContain(`import { config as configExtension, configDoctor, files } from '@liche/config'`)
    expect(source).toContain(`extensions: [help(), version(), outputControls({ json: true, fullOutput: true, filterOutput: true }), reflectionControls({ schema: true }), llms({ commands: { include: [] } }), configExtension({`)
    expect(source).toContain(`files: ['p.jsonc'],`)
    expect(source).toContain(`sources: { options: { 'zone': [{ provider: 'config', path: 'defaultZone' }] } },`)
    const purgeBlock = extractCommandBlock(source, 'purge')
    expect(purgeBlock).toContain(`const remoteBaseUrl = ctx.sources.value('config', 'apiBaseUrl')`)
    expect(purgeBlock).toContain(`code: 'REMOTE_CONFIG_MISSING_BASE_URL'`)
    expect(purgeBlock).toContain(`code_actions: [{ title: 'Inspect config', argv: ['config', 'doctor'] }]`)
    expect(purgeBlock).toContain(`suggested_fix: 'Set apiBaseUrl in config before retrying.'`)
    expect(purgeBlock).toContain(`const remoteBaseUrlSource = ctx.sources.source('config', 'apiBaseUrl').kind === 'default' ? 'schema-default' : 'config'`)
    expect(purgeBlock).toContain(`const data = await callHttpOperation({`)
    expect(purgeBlock).toContain(`baseUrl: remoteBaseUrl,`)
    expect(purgeBlock).toContain(`method: 'POST',`)
    expect(purgeBlock).toContain(`path: '/zones/{zone}/purge',`)
    expect(purgeBlock).toContain(`bind: { path: ['zone'], body: false },`)
    expect(purgeBlock).toContain(`execution: { mode: 'remote-http', source: remoteBaseUrlSource }`)
    expect(purgeBlock).not.toContain(`REMOTE_NOT_IMPLEMENTED`)
  })

  test('local handlers from the same module deduplicate to one import per export', () => {
    const cat = normalizeProduct(
      defineProduct({
        id: 'p',
        name: 'P',
        version: '0.1.0',
        auth: Auth.none(),
        commands: {
          a: Command.local({ summary: 'a', handler: 'm.run' }),
          b: Command.local({ summary: 'b', handler: 'm.run' }),
        },
      }),
    )
    const source = generate(cat)
    expect(source.match(/from '\.\/impl\/m\.js'/g)).toHaveLength(1)
    expect(source).toContain(`import { run } from './impl/m.js'`)
  })
})

describe('generateCli — list output resolution', () => {
  test('Shape.list("script") output renders as z.array(z.object(...)) using the resource fields', () => {
    const source = generate(workersCatalog())
    const listBlock = extractCommandBlock(source, ['script', 'list'])
    expect(listBlock).toMatch(/output: z\.array\(z\.object\(/)
    expect(listBlock).toContain(`'id':`)
    expect(listBlock).toContain(`'name':`)
  })

  test('broken list-shape resource reference is reported by the generator, not silently emitted', () => {
    const product = defineProduct({
      id: 'p',
      name: 'P',
      version: '0.1.0',
      auth: Auth.none(),
      remote: { baseUrl: Runtime.literal('https://api.example.test') },
      resources: {
        orphan: {
          label: 'o',
          path: '/o',
          operations: {
            list: {
          summary: 'List',
          http: { method: 'GET', path: '' },
          // points at a resource that does not exist in this catalog
          output: Shape.list('ghost'),
            },
          },
        },
      },
    })
    expect(() => generate(normalizeProduct(product))).toThrow(
      /resource 'ghost' is not declared in this catalog/,
    )
  })
})

describe('generateCli — dev is not treated as HTTP-capable', () => {
  test('dev command never emits remote dispatch or HTTP path references', () => {
    const source = generate(workersCatalog())
    const devBlock = extractCommandBlock(source, 'dev')
    expect(devBlock).not.toContain('REMOTE_NOT_IMPLEMENTED')
    expect(devBlock).not.toMatch(/method: 'GET'|method: 'POST'/)
    expect(devBlock).not.toContain('http')
  })

  test('deploy renders as a top-level hybrid-workflow command, not a fake resource mutation', () => {
    const source = generate(workersCatalog())
    // deploy is part of the root declarative command array, not nested in a
    // sub-Cli. Assert it appears after the root defineCli block opens.
    const rootStart = source.indexOf('const cli = defineCli({')
    expect(rootStart).toBeGreaterThan(-1)
    const deployIdx = source.indexOf(`path: ['deploy'],`)
    expect(deployIdx).toBeGreaterThan(rootStart)

    const scriptListIdx = source.indexOf(`path: ['script', 'list'],`)
    expect(scriptListIdx).toBeGreaterThan(rootStart)
    expect(deployIdx).toBeGreaterThan(scriptListIdx)
  })
})

// Extract one defineCommand({ path: [...] }) block by simple brace-balance scan.
function extractCommandBlock(source: string, commandPath: string | string[]): string {
  const path = Array.isArray(commandPath) ? commandPath : [commandPath]
  const marker = `path: ${renderTestStringArray(path)},`
  const pathStart = source.indexOf(marker)
  if (pathStart === -1) throw new Error(`Command '${path.join(' ')}' not found in generated source`)
  const start = source.lastIndexOf('defineCommand({', pathStart)
  if (start === -1) throw new Error(`Command '${path.join(' ')}' has no defineCommand wrapper`)
  let depth = 0
  let i = source.indexOf('{', start)
  for (; i < source.length; i++) {
    const ch = source[i]
    if (ch === '{') depth += 1
    else if (ch === '}') {
      depth -= 1
      if (depth === 0) {
        i += 1
        break
      }
    }
  }
  return source.slice(start, i)
}

function renderTestStringArray(values: string[]): string {
  return `[${values.map((value) => `'${value}'`).join(', ')}]`
}
