import { describe, expect, test } from 'bun:test'
import {
  Auth,
  Command,
  Config,
  Field,
  Product,
  Runtime,
  Shape,
  canonicalDigest,
  generateCli,
  normalizeProduct,
} from '../src/index.js'
import type { Catalog } from '../src/index.js'

function workersCatalog(): Catalog {
  const product = Product.create({
    id: 'workers',
    name: 'Workers',
    version: '1.0.0',
  })
    .auth(Auth.none())
    .resource('script', { label: 'Worker script', path: '/workers/scripts' }, (r) =>
      r
        .field('id', Field.string('Script ID').identifier().immutable())
        .field('name', Field.string('Script name').humanLabel())
        .operation('list', {
          summary: 'List Worker scripts',
          http: { method: 'GET', path: '' },
          output: Shape.list('script'),
        }),
    )
    .command(
      'deploy',
      Command.workflow({
        summary: 'Deploy a Worker',
        input: Shape.object({
          entrypoint: Field.string('Entrypoint file'),
          environment: Field.string('Environment').optional(),
        }),
        output: Shape.object({ deployment_id: Field.string('Deployment ID') }),
        handler: 'wrangler.deploy',
      }),
    )
    .command(
      'dev',
      Command.local({
        summary: 'Run a local development server',
        input: Shape.object({ entrypoint: Field.string('Entrypoint file') }),
        output: Shape.object({ url: Field.string('Local URL') }),
        handler: 'wrangler.dev',
      }),
    )
  return normalizeProduct(product)
}

function generate(catalog: Catalog): string {
  return generateCli(catalog, {
    generatorVersion: '0.0.0',
    canonicalIrDigest: canonicalDigest(catalog),
    generationOptionsDigest: canonicalDigest({ surfaceId: 'cli' }),
  })
}

describe('generateCli — header', () => {
  test('header records source=catalog and product@version, not contract@version', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(' * @generated by @lili/product 0.0.0')
    expect(source).toContain(' * product: workers@1.0.0')
    expect(source).toContain(' * canonical-catalog-digest:')
    expect(source).toContain(' * source: catalog')
    expect(source).not.toContain('schema: workers')
    expect(source).not.toContain('source: canonical-ir')
  })
})

describe('generateCli — imports', () => {
  test('imports Cli and z from @lili/core exactly once', () => {
    const source = generate(workersCatalog())
    const coreImports = [...source.matchAll(/from '@lili\/core'/g)]
    expect(coreImports).toHaveLength(1)
    const importLine = source.match(/import \{ ([^}]+) \} from '@lili\/core'/)
    expect(importLine?.[1]).toBe('Cli, z')
  })

  test('local and hybrid-workflow handlers are imported from ./impl/<module>.js, grouped per module', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`import { deploy, dev } from './impl/wrangler.js'`)
  })

  test('no handler imports are emitted for resource operations (HTTP, no handler binding)', () => {
    const source = generate(workersCatalog())
    expect(source).not.toMatch(/from '\.\/impl\/script\.js'/)
  })

  test('two distinct handler modules emit two grouped import lines in module-sorted order', () => {
    const cat = normalizeProduct(
      Product.create({ id: 'p', name: 'P', version: '0.1.0' })
        .auth(Auth.none())
        .command('login', Command.local({ summary: 'login', handler: 'auth.login' }))
        .command('dev', Command.local({ summary: 'dev', handler: 'wrangler.dev' })),
    )
    const source = generate(cat)
    const authIdx = source.indexOf(`from './impl/auth.js'`)
    const wranglerIdx = source.indexOf(`from './impl/wrangler.js'`)
    expect(authIdx).toBeGreaterThan(-1)
    expect(wranglerIdx).toBeGreaterThan(-1)
    expect(authIdx).toBeLessThan(wranglerIdx)
  })

  test('handler strings must be of the form module.export; bare strings fail loudly', () => {
    const product = Product.create({ id: 'p', name: 'P', version: '0.1.0' }).auth(Auth.none()).command(
      'dev',
      Command.local({ summary: 'dev', handler: 'broken' }),
    )
    expect(() => generate(normalizeProduct(product))).toThrow(
      /Handler 'broken' must be of the form 'module\.export'/,
    )
  })
})

describe('generateCli — command tree shape', () => {
  test('resource operations are registered under a sub-Cli named after the resource id', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`const script = Cli.create('script')`)
    expect(source).toMatch(/\.command\('list', \{/)
    // The script sub-Cli is .command()-ed into the root.
    expect(source).toContain(`  .command(script)`)
  })

  test('top-level commands chain directly on the root Cli without a sub-Cli wrapper', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`  .command('deploy', {`)
    expect(source).toContain(`  .command('dev', {`)
    expect(source).not.toContain(`const deploy = Cli.create('deploy')`)
    expect(source).not.toContain(`const dev = Cli.create('dev')`)
  })

  test('root Cli carries product id+version and the generated envelope/disabledGlobals contract', () => {
    const source = generate(workersCatalog())
    expect(source).toContain(`const cli = Cli.create({`)
    expect(source).toContain(`  name: 'workers',`)
    expect(source).toContain(`  version: '1.0.0',`)
    expect(source).toContain(`  generated: { machineOutput: 'envelope', disabledGlobals: ['format'] },`)
  })
})

describe('generateCli — run bodies by execution mode', () => {
  test('local command run body calls the exported handler with ctx.options and tags meta.execution.mode=local', () => {
    const source = generate(workersCatalog())
    // The dev command should look like: const data = await dev(ctx.options); return ctx.ok(data, { execution: { mode: 'local', ...
    const devBlock = extractCommandBlock(source, 'dev')
    expect(devBlock).toMatch(/const data = await dev\(ctx\.options\)/)
    expect(devBlock).toMatch(/execution: \{ mode: 'local', source: 'schema-default' \}/)
  })

  test('hybrid-workflow command run body calls the handler and tags meta.execution.mode=hybrid-workflow', () => {
    const source = generate(workersCatalog())
    const deployBlock = extractCommandBlock(source, 'deploy')
    expect(deployBlock).toMatch(/const data = await deploy\(ctx\.options\)/)
    expect(deployBlock).toMatch(/execution: \{ mode: 'hybrid-workflow', source: 'schema-default' \}/)
  })

  test('resource operation run body is a Phase 4 not-implemented stub, not a fake handler call', () => {
    const source = generate(workersCatalog())
    const listBlock = extractCommandBlock(source, 'list')
    expect(listBlock).toContain(`code: 'REMOTE_NOT_IMPLEMENTED'`)
    expect(listBlock).toMatch(/resource operations is not implemented yet \(Phase 4\)/)
    expect(listBlock).not.toMatch(/await \w+\(ctx\.options\)/)
  })

  test('remote-http command run body is a Phase 4 not-implemented stub', () => {
    const cat = normalizeProduct(
      Product.create({ id: 'p', name: 'P', version: '0.1.0' }).auth(Auth.none()).command(
        'purge',
        Command.remoteHttp({ summary: 'Purge', http: { method: 'POST', path: '/purge' } }),
      ),
    )
    const source = generate(cat)
    const purgeBlock = extractCommandBlock(source, 'purge')
    expect(purgeBlock).toContain(`code: 'REMOTE_NOT_IMPLEMENTED'`)
    expect(purgeBlock).toMatch(/remote-http commands is not implemented yet \(Phase 4\)/)
  })

  test('remote-http command with product remote config calls core HTTP transport', () => {
    const cat = normalizeProduct(
      Product.create({ id: 'p', name: 'P', version: '0.1.0' })
        .auth(Auth.none())
        .config(Config.object({
          files: ['p.jsonc'],
          fields: Shape.object({
            apiBaseUrl: Field.string('API base URL').default('https://api.example.test'),
            defaultZone: Field.string('Default zone').optional(),
          }),
          scopes: { project: { discoverUpwards: true }, user: false },
        }))
        .remote({ baseUrl: Runtime.config('apiBaseUrl') })
        .command(
          'purge',
          Command.remoteHttp({
            summary: 'Purge',
            input: Shape.object({
              zone: Field.string('Zone').fromConfig('defaultZone'),
            }),
            output: Shape.object({ purge_id: Field.string('Purge ID') }),
            http: { method: 'POST', path: '/zones/{zone}/purge', bind: { path: ['zone'] } },
          }),
        ),
    )
    const source = generate(cat)
    expect(source.match(/from '@lili\/core'/)?.[0]).toBe("from '@lili/core'")
    expect(source).toContain(`import { Cli, Config, callHttpOperation, z } from '@lili/core'`)
    expect(source).toContain(`config: Config.object({`)
    expect(source).toContain(`files: ['p.jsonc'],`)
    expect(source).toContain(`optionConfig: { 'zone': 'defaultZone' },`)
    const purgeBlock = extractCommandBlock(source, 'purge')
    expect(purgeBlock).toContain(`const data = await callHttpOperation({`)
    expect(purgeBlock).toContain(`baseUrl: ctx.config['apiBaseUrl'] as string,`)
    expect(purgeBlock).toContain(`method: 'POST',`)
    expect(purgeBlock).toContain(`path: '/zones/{zone}/purge',`)
    expect(purgeBlock).toContain(`bind: { path: ['zone'], body: false },`)
    expect(purgeBlock).not.toContain(`REMOTE_NOT_IMPLEMENTED`)
  })

  test('local handlers from the same module deduplicate to one import per export', () => {
    const cat = normalizeProduct(
      Product.create({ id: 'p', name: 'P', version: '0.1.0' })
        .auth(Auth.none())
        .command('a', Command.local({ summary: 'a', handler: 'm.run' }))
        .command('b', Command.local({ summary: 'b', handler: 'm.run' })),
    )
    const source = generate(cat)
    expect(source.match(/from '\.\/impl\/m\.js'/g)).toHaveLength(1)
    expect(source).toContain(`import { run } from './impl/m.js'`)
  })
})

describe('generateCli — list output resolution', () => {
  test('Shape.list("script") output renders as z.array(z.object(...)) using the resource fields', () => {
    const source = generate(workersCatalog())
    const listBlock = extractCommandBlock(source, 'list')
    expect(listBlock).toMatch(/output: z\.array\(z\.object\(/)
    expect(listBlock).toContain(`'id':`)
    expect(listBlock).toContain(`'name':`)
  })

  test('broken list-shape resource reference is reported by the generator, not silently emitted', () => {
    const product = Product.create({ id: 'p', name: 'P', version: '0.1.0' }).auth(Auth.none()).resource(
      'orphan',
      { label: 'o', path: '/o' },
      (r) =>
        r.operation('list', {
          summary: 'List',
          http: { method: 'GET', path: '' },
          // points at a resource that does not exist in this catalog
          output: Shape.list('ghost'),
        }),
    )
    expect(() => generate(normalizeProduct(product))).toThrow(
      /resource 'ghost' is not declared in this catalog/,
    )
  })
})

describe('generateCli — dev is not treated as HTTP-capable', () => {
  test('dev command never emits remote dispatch or HTTP path references', () => {
    const source = generate(workersCatalog())
    const devBlock = extractCommandBlock(source, 'dev')
    expect(devBlock).not.toContain('REMOTE_NOT_IMPLEMENTED')
    expect(devBlock).not.toMatch(/method: 'GET'|method: 'POST'/)
    expect(devBlock).not.toContain('http')
  })

  test('deploy renders as a top-level hybrid-workflow command, not a fake resource mutation', () => {
    const source = generate(workersCatalog())
    // deploy is part of the root Cli.create({...}) chain, not nested in a
    // sub-Cli. Assert it appears AFTER the root Cli.create block opens.
    const rootStart = source.indexOf('const cli = Cli.create({')
    expect(rootStart).toBeGreaterThan(-1)
    const deployIdx = source.indexOf(`.command('deploy', {`)
    expect(deployIdx).toBeGreaterThan(rootStart)

    // deploy must NOT appear inside the `script` resource sub-Cli block.
    const scriptBlock = source.slice(
      source.indexOf(`const script = Cli.create('script')`),
      rootStart,
    )
    expect(scriptBlock).not.toContain(`.command('deploy'`)
  })
})

// Extract one .command('name', { ... }) block by simple brace-balance scan.
function extractCommandBlock(source: string, commandName: string): string {
  const marker = `.command('${commandName}', {`
  const start = source.indexOf(marker)
  if (start === -1) throw new Error(`Command '${commandName}' not found in generated source`)
  let depth = 0
  let i = start + marker.length - 1 // pointer at the opening `{`
  for (; i < source.length; i++) {
    const ch = source[i]
    if (ch === '{') depth += 1
    else if (ch === '}') {
      depth -= 1
      if (depth === 0) {
        i += 1
        break
      }
    }
  }
  return source.slice(start, i)
}
